bindPort = 7005
# Specify a UDP port for QUIC.
quicBindPort = 7005


# Heartbeat configure, it's not recommended to modify the default value
# The default value of heartbeatTimeout is 90. Set negative value to disable it.
# transport.heartbeatTimeout = 90

# Pool count in each proxy will keep no more than maxPoolCount.
transport.maxPoolCount = 3

# If tcp stream multiplexing is used, default is true
transport.tcpMux = true

# Specify keep alive interval for tcp mux.
# only valid if tcpMux is true.
transport.tcpMuxKeepaliveInterval = 30

# tcpKeepalive specifies the interval between keep-alive probes for an active network connection between frpc and frps.
# If negative, keep-alive probes are disabled.
transport.tcpKeepalive = 7200


# transport.tls.force specifies whether to only accept TLS-encrypted connections. By default, the value is false.
transport.tls.force = true

transport.tls.certFile = "/server.crt"
transport.tls.keyFile = "/server.key"
transport.tls.trustedCaFile = "/ca.crt"

# If you want to support virtual host, you must set the http port for listening (optional)
# Note: http port and https port can be same with bindPort
#vhostHTTPPort = 80
#vhostHTTPPort = 5080
#vhostHTTPSPort = 5001

# Response header timeout(seconds) for vhost http server, default is 60s
# vhostHTTPTimeout = 60


# auth.method specifies what authentication method to use authenticate frpc with frps.
# If "token" is specified - token will be read into login message.
# If "oidc" is specified - OIDC (Open ID Connect) token will be issued using OIDC settings. By default, this value is "token".
auth.method = "token"

# auth token
auth.token = "12345678"

# Only allow frpc to bind ports you list. By default, there won't be any limit.
#allowPorts = [
#  { single = 65523 }, # Reserve 65523 for final deployment
#  { single = 65525 }, # Reserve 65525 for maintenance 
#  { single = 65522 }, # Reserve 65522 for final deployment
#  { single = 65524 }, # Reserve 65524 for maintenance
#  { start = 2000, end = 3000 },
#  { single = 3001 },
#  { single = 3003 },
#  { start = 4000, end = 50000 }
#]


# Max ports can be used for each client, default value is 0 means no limit
maxPortsPerClient = 0

# If subDomainHost is not empty, you can set subdomain when type is http or https in frpc's configure file
# When subdomain is test, the host used by routing is test.frps.com
subDomainHost = "frps.com"

